
using TimeNowWorld.Models;

namespace TimeNowWorld.Data;

public class BackupData
{
    public static List<Country> ListCountries()
    {
        List<Country> list = new();
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC-10:00", Territory = "Society Islands, Tuamotus, Austral Islands", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC-09:30", Territory = "Marquesas Islands", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC-09:00", Territory = "Gambier Islands", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC-08:00", Territory = "Clipperton Island", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC-04:00", Territory = "AST", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC-03:00", Territory = "PMST", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "CET", Default = true });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC+03:00", Territory = "Mayotte, Scattered Islands in the Indian Ocean", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC+04:00", Territory = "Réunion, Crozet Islands", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC+05:00", Territory = "Kerguelen Islands, Saint Paul and Amsterdam Islands", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC+10:00", Territory = "Adélie Land", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC+11:00", Territory = "New Caledonia", Default = false });
        list.Add(new Country() { IdCountry = 1, NameEN = "France", NameES = "Francia", Capital = "Paris", Continent = "Europa", TimeZone = "UTC+12:00", Territory = "Wallis and Futuna", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "Kaliningrad Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+03:00", Territory = "Moscow Time", Default = true });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+04:00", Territory = "Samara Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+05:00", Territory = "Yekaterinburg Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+06:00", Territory = "Omsk Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+07:00", Territory = "Krasnoyarsk Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+08:00", Territory = "Irkutsk Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+09:00", Territory = "Yakutsk Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+10:00", Territory = "Vladivostok Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+11:00", Territory = "Magadan Time", Default = false });
        list.Add(new Country() { IdCountry = 2, NameEN = "Russia", NameES = "Rusia", Capital = "Moscu", Continent = "Europa", TimeZone = "UTC+12:00", Territory = "Kamchatka Time", Default = false });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC-11:00", Territory = "ST", Default = false });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC-10:00", Territory = "HT", Default = false });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC-09:00", Territory = "AKT", Default = false });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC-08:00", Territory = "PT", Default = false });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC-07:00", Territory = "MT", Default = false });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC-06:00", Territory = "CT", Default = true });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC-05:00", Territory = "ET", Default = false });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC-04:00", Territory = "AST", Default = false });
        list.Add(new Country() { IdCountry = 3, NameEN = "United States", NameES = "Estados Unidos", Capital = "Washington D. C.", Continent = "América", TimeZone = "UTC+10:00", Territory = "ChT", Default = false });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+05:00", Territory = "Heard and McDonald Islands", Default = false });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+06:30", Territory = "Cocos", Default = false });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+07:00", Territory = "CXT", Default = false });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+08:00", Territory = "AWST", Default = false });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+08:45", Territory = "CWT", Default = false });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+09:30", Territory = "ACST", Default = false });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+10:00", Territory = "AEST", Default = true });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+10:30", Territory = "Lord Howe Island", Default = false });
        list.Add(new Country() { IdCountry = 4, NameEN = "Australia", NameES = "Australia", Capital = "Canberra", Continent = "Oceanía", TimeZone = "UTC+11:00", Territory = "NFT", Default = false });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC-08:00", Territory = "Pitcairn Islands", Default = false });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC-05:00", Territory = "Cayman Islands", Default = false });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC-04:00", Territory = "AST", Default = false });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC-03:00", Territory = "FKST", Default = false });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC-02:00", Territory = "South Georgia and the South Sandwich Islands", Default = false });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC+00:00", Territory = "GTM", Default = true });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "CET", Default = false });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "EET", Default = false });
        list.Add(new Country() { IdCountry = 5, NameEN = "United Kingdom", NameES = "Reino Unido", Capital = "Londres", Continent = "Europa", TimeZone = "UTC+06:00", Territory = "British Indian Ocean Territory", Default = false });
        list.Add(new Country() { IdCountry = 6, NameEN = "Canada", NameES = "Canada", Capital = "Ottawa", Continent = "América", TimeZone = "UTC-08:00", Territory = "PT", Default = false });
        list.Add(new Country() { IdCountry = 6, NameEN = "Canada", NameES = "Canada", Capital = "Ottawa", Continent = "América", TimeZone = "UTC-07:00", Territory = "MT", Default = true });
        list.Add(new Country() { IdCountry = 6, NameEN = "Canada", NameES = "Canada", Capital = "Ottawa", Continent = "América", TimeZone = "UTC-06:00", Territory = "CT", Default = false });
        list.Add(new Country() { IdCountry = 6, NameEN = "Canada", NameES = "Canada", Capital = "Ottawa", Continent = "América", TimeZone = "UTC-05:00", Territory = "ET", Default = false });
        list.Add(new Country() { IdCountry = 6, NameEN = "Canada", NameES = "Canada", Capital = "Ottawa", Continent = "América", TimeZone = "UTC-04:00", Territory = "AT", Default = false });
        list.Add(new Country() { IdCountry = 6, NameEN = "Canada", NameES = "Canada", Capital = "Ottawa", Continent = "América", TimeZone = "UTC-03:30", Territory = "NT", Default = false });
        list.Add(new Country() { IdCountry = 7, NameEN = "Denmark", NameES = "Dinamarca", Capital = "Copenhague", Continent = "Europa", TimeZone = "UTC-04:00", Territory = "Thule Air Base in Greenland", Default = false });
        list.Add(new Country() { IdCountry = 7, NameEN = "Denmark", NameES = "Dinamarca", Capital = "Copenhague", Continent = "Europa", TimeZone = "UTC-03:00", Territory = " Greenland", Default = false });
        list.Add(new Country() { IdCountry = 7, NameEN = "Denmark", NameES = "Dinamarca", Capital = "Copenhague", Continent = "Europa", TimeZone = "UTC-01:00", Territory = "Ittoqqortoormiit", Default = false });
        list.Add(new Country() { IdCountry = 7, NameEN = "Denmark", NameES = "Dinamarca", Capital = "Copenhague", Continent = "Europa", TimeZone = "UTC+00:00", Territory = "Danmarkshavn", Default = false });
        list.Add(new Country() { IdCountry = 7, NameEN = "Denmark", NameES = "Dinamarca", Capital = "Copenhague", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "CET", Default = true });
        list.Add(new Country() { IdCountry = 8, NameEN = "New Zealand", NameES = "Nueva Zelanda", Capital = "Wellington", Continent = "Oceanía", TimeZone = "UTC-11:00", Territory = "Niue", Default = false });
        list.Add(new Country() { IdCountry = 8, NameEN = "New Zealand", NameES = "Nueva Zelanda", Capital = "Wellington", Continent = "Oceanía", TimeZone = "UTC-10:00", Territory = "Cook Islands", Default = false });
        list.Add(new Country() { IdCountry = 8, NameEN = "New Zealand", NameES = "Nueva Zelanda", Capital = "Wellington", Continent = "Oceanía", TimeZone = "UTC+12:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 8, NameEN = "New Zealand", NameES = "Nueva Zelanda", Capital = "Wellington", Continent = "Oceanía", TimeZone = "UTC+12:45", Territory = "Chatham Islands", Default = false });
        list.Add(new Country() { IdCountry = 8, NameEN = "New Zealand", NameES = "Nueva Zelanda", Capital = "Wellington", Continent = "Oceanía", TimeZone = "UTC+13:00", Territory = "Tokelau", Default = false });
        list.Add(new Country() { IdCountry = 9, NameEN = "Brazil", NameES = "Brasil", Capital = "Brasilia", Continent = "América", TimeZone = "UTC-05:00", Territory = "Brasília time -2", Default = false });
        list.Add(new Country() { IdCountry = 9, NameEN = "Brazil", NameES = "Brasil", Capital = "Brasilia", Continent = "América", TimeZone = "UTC-04:00", Territory = "Brasília time -1", Default = false });
        list.Add(new Country() { IdCountry = 9, NameEN = "Brazil", NameES = "Brasil", Capital = "Brasilia", Continent = "América", TimeZone = "UTC-03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 9, NameEN = "Brazil", NameES = "Brasil", Capital = "Brasilia", Continent = "América", TimeZone = "UTC-02:00", Territory = "Brasília time +1", Default = false });
        list.Add(new Country() { IdCountry = 10, NameEN = "Mexico", NameES = "Mexico", Capital = "México D. F.", Continent = "América", TimeZone = "UTC-08:00", Territory = "Northwest Zone", Default = false });
        list.Add(new Country() { IdCountry = 10, NameEN = "Mexico", NameES = "Mexico", Capital = "México D. F.", Continent = "América", TimeZone = "UTC-07:00", Territory = "Pacific Zone", Default = false });
        list.Add(new Country() { IdCountry = 10, NameEN = "Mexico", NameES = "Mexico", Capital = "México D. F.", Continent = "América", TimeZone = "UTC-06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 10, NameEN = "Mexico", NameES = "Mexico", Capital = "México D. F.", Continent = "América", TimeZone = "UTC-05:00", Territory = "Southeast Zone", Default = false });
        list.Add(new Country() { IdCountry = 11, NameEN = "Chile", NameES = "Chile", Capital = "Santiago De Chile", Continent = "América", TimeZone = "UTC-06:00", Territory = "Easter Island", Default = false });
        list.Add(new Country() { IdCountry = 11, NameEN = "Chile", NameES = "Chile", Capital = "Santiago De Chile", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 11, NameEN = "Chile", NameES = "Chile", Capital = "Santiago De Chile", Continent = "América", TimeZone = "UTC-03:00", Territory = "Magallanes and Chilean Antarctica", Default = false });
        list.Add(new Country() { IdCountry = 12, NameEN = "Indonesia", NameES = "Indonesia", Capital = "Yakarta", Continent = "Asia", TimeZone = "UTC+07:00", Territory = "Western", Default = true });
        list.Add(new Country() { IdCountry = 12, NameEN = "Indonesia", NameES = "Indonesia", Capital = "Yakarta", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "Central", Default = false });
        list.Add(new Country() { IdCountry = 12, NameEN = "Indonesia", NameES = "Indonesia", Capital = "Yakarta", Continent = "Asia", TimeZone = "UTC+09:00", Territory = "Eastern", Default = false });
        list.Add(new Country() { IdCountry = 13, NameEN = "Kiribati", NameES = "Kiribati", Capital = "Tarawa", Continent = "Oceanía", TimeZone = "UTC+12:00", Territory = "Gilbert Islands", Default = true });
        list.Add(new Country() { IdCountry = 13, NameEN = "Kiribati", NameES = "Kiribati", Capital = "Tarawa", Continent = "Oceanía", TimeZone = "UTC+13:00", Territory = "Phoenix Islands", Default = false });
        list.Add(new Country() { IdCountry = 13, NameEN = "Kiribati", NameES = "Kiribati", Capital = "Tarawa", Continent = "Oceanía", TimeZone = "UTC+14:00", Territory = "Line Islands", Default = false });
        list.Add(new Country() { IdCountry = 14, NameEN = "Democratic Republic of the Congo", NameES = "República Democrática Del Congo", Capital = "Kinshasa", Continent = "África", TimeZone = "UTC+01:00", Territory = "WAT", Default = true });
        list.Add(new Country() { IdCountry = 14, NameEN = "Democratic Republic of the Congo", NameES = "República Democrática Del Congo", Capital = "Kinshasa", Continent = "África", TimeZone = "UTC+02:00", Territory = "CAT", Default = false });
        list.Add(new Country() { IdCountry = 15, NameEN = "Ecuador", NameES = "Ecuador", Capital = "Quito", Continent = "América", TimeZone = "UTC-06:00", Territory = "GALT", Default = false });
        list.Add(new Country() { IdCountry = 15, NameEN = "Ecuador", NameES = "Ecuador", Capital = "Quito", Continent = "América", TimeZone = "UTC-05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 16, NameEN = "Federated States of Micronesia", NameES = "Micronesia", Capital = "Palikir", Continent = "Oceanía", TimeZone = "UTC+10:00", Territory = "Chuuk and Yap", Default = false });
        list.Add(new Country() { IdCountry = 16, NameEN = "Federated States of Micronesia", NameES = "Micronesia", Capital = "Palikir", Continent = "Oceanía", TimeZone = "UTC+11:00", Territory = "Kosrae and Pohnpei", Default = true });
        list.Add(new Country() { IdCountry = 17, NameEN = "Kazakhstan", NameES = "Kazajistán", Capital = "Astaná", Continent = "Asia", TimeZone = "UTC+05:00", Territory = "Western", Default = false });
        list.Add(new Country() { IdCountry = 17, NameEN = "Kazakhstan", NameES = "Kazajistán", Capital = "Astaná", Continent = "Asia", TimeZone = "UTC+06:00", Territory = "Eastern", Default = true });
        list.Add(new Country() { IdCountry = 18, NameEN = "Kingdom of the Netherlands", NameES = "Países Bajos", Capital = "Amsterdam", Continent = "Europa", TimeZone = "UTC-04:00", Territory = "AST", Default = false });
        list.Add(new Country() { IdCountry = 18, NameEN = "Kingdom of the Netherlands", NameES = "Países Bajos", Capital = "Amsterdam", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "CET", Default = true });
        list.Add(new Country() { IdCountry = 19, NameEN = "Mongolia", NameES = "Mongolia", Capital = "Ulan Bator", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 20, NameEN = "Papua New Guinea", NameES = "Papúa Nueva Guinea", Capital = "Port Moresby", Continent = "Oceanía", TimeZone = "UTC+10:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 21, NameEN = "Portugal", NameES = "Portugal", Capital = "Lisboa", Continent = "Europa", TimeZone = "UTC-01:00", Territory = "Azores", Default = false });
        list.Add(new Country() { IdCountry = 21, NameEN = "Portugal", NameES = "Portugal", Capital = "Lisboa", Continent = "Europa", TimeZone = "UTC+00:00", Territory = "WET", Default = true });
        list.Add(new Country() { IdCountry = 22, NameEN = "South Africa", NameES = "Sudáfrica", Capital = "Pretoria, Ciudad Del Cabo, Bloemfontein", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 22, NameEN = "South Africa", NameES = "Sudáfrica", Capital = "Pretoria, Ciudad Del Cabo, Bloemfontein", Continent = "África", TimeZone = "UTC+03:00", Territory = "Prince Edward Islands", Default = false });
        list.Add(new Country() { IdCountry = 23, NameEN = "Spain", NameES = "España", Capital = "Madrid", Continent = "Europa", TimeZone = "UTC+00:00", Territory = "WET", Default = false });
        list.Add(new Country() { IdCountry = 23, NameEN = "Spain", NameES = "España", Capital = "Madrid", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 24, NameEN = "Ukraine", NameES = "Ucrania", Capital = "Kiev", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 25, NameEN = "Afghanista", NameES = "Afganistán", Capital = "Kabul", Continent = "Asia", TimeZone = "UTC+04:30", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 26, NameEN = "Albania", NameES = "Albania", Capital = "Tirana", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 27, NameEN = "Algeria", NameES = "Argelia", Capital = "Argel", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 28, NameEN = "Andorra", NameES = "Andorra", Capital = "Andorra La Vieja", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 29, NameEN = "Angola", NameES = "Angola", Capital = "Luanda", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 30, NameEN = "Antigua and Barbuda", NameES = "Antigua V Barbuda", Capital = "Saint John'S", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 31, NameEN = "Argentina", NameES = "Argentina", Capital = "Buenos Aires", Continent = "América", TimeZone = "UTC-03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 32, NameEN = "Armenia", NameES = "Armenia", Capital = "Ereván", Continent = "Europa", TimeZone = "UTC+04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 33, NameEN = "Austria", NameES = "Austria", Capital = "Viena", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 34, NameEN = "Azerbaijan", NameES = "Azerbaiyán", Capital = "Bakú", Continent = "Europa", TimeZone = "UTC+04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 35, NameEN = "Bahamas", NameES = "Bahamas", Capital = "Nassau", Continent = "América", TimeZone = "UTC-05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 36, NameEN = "Bahrain", NameES = "Baréin", Capital = "Manamá", Continent = "Asia", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 37, NameEN = "Bangladesh", NameES = "Bangladés", Capital = "Daca", Continent = "Asia", TimeZone = "UTC+06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 38, NameEN = "Barbados", NameES = "Barbados", Capital = "Bridgetown", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 39, NameEN = "Belarus", NameES = "Bielorrusia", Capital = "Minsk", Continent = "Europa", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 40, NameEN = "Belgium", NameES = "Bélgica", Capital = "Bruselas", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 41, NameEN = "Belize", NameES = "Belice", Capital = "Belmopán", Continent = "América", TimeZone = "UTC-06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 42, NameEN = "Benin", NameES = "Benin", Capital = "Porto-Novo", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 43, NameEN = "Bhutan", NameES = "Bután", Capital = "Timbu", Continent = "Asia", TimeZone = "UTC+06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 44, NameEN = "Bolivia", NameES = "Bolivia", Capital = "Sucre, La Paz", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 45, NameEN = "Bosnia and Herzegovina", NameES = "Bosnia y Herzegovina", Capital = "Sarajevo", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 46, NameEN = "Botswana", NameES = "Botsuana", Capital = "Gaberones", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 47, NameEN = "Brunei", NameES = "Brunei", Capital = "Bandar Seri Begawan", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 48, NameEN = "Bulgaria", NameES = "Bulgaria", Capital = "Sofía", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 49, NameEN = "Burkina Faso", NameES = "Burkina Faso", Capital = "Uagadugú", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 50, NameEN = "Burundi", NameES = "Burundi", Capital = "Buyumbura", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 51, NameEN = "Cambodia", NameES = "Camboya", Capital = "Pnon Pehn", Continent = "Asia", TimeZone = "UTC+07:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 52, NameEN = "Cameroon", NameES = "Camerún", Capital = "Yaundé", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 53, NameEN = "Cape Verde", NameES = "Cabo Verde", Capital = "Praia", Continent = "África", TimeZone = "UTC-01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 54, NameEN = "Central African Republic", NameES = "República Centroafricana", Capital = "Bangui", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 55, NameEN = "Chad", NameES = "Chad", Capital = "Yamena", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 56, NameEN = "China", NameES = "China", Capital = "Pekín", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 57, NameEN = "Colombia", NameES = "Colombia", Capital = "Bogotá", Continent = "América", TimeZone = "UTC-05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 58, NameEN = "Comoros", NameES = "Comoras", Capital = "Moroni", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 59, NameEN = "Republic of the Congo", NameES = "República Del Congo", Capital = "Brazzaville", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 60, NameEN = "Costa Rica", NameES = "Costa Rica", Capital = "San José", Continent = "América", TimeZone = "UTC-06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 61, NameEN = "Croatia", NameES = "Croacia", Capital = "Zagreb", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 62, NameEN = "Cuba", NameES = "Cuba", Capital = "La Habana", Continent = "América", TimeZone = "UTC-05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 63, NameEN = "Cyprus", NameES = "Chipre", Capital = "Nicosia", Continent = "Asia", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 64, NameEN = "Czech Republic", NameES = "República Checa", Capital = "Praga", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 65, NameEN = "Djibouti", NameES = "Yibuti", Capital = "Yibuti", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 66, NameEN = "Dominica", NameES = "Dominica", Capital = "Roseau", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 67, NameEN = "Dominican Republic", NameES = "República Dominicana", Capital = "Santo Domingo", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 68, NameEN = "East Timor", NameES = "Timor Oriental", Capital = "Dili", Continent = "Asia", TimeZone = "UTC+09:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 69, NameEN = "Egypt", NameES = "Egipto", Capital = "El Cairo", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 70, NameEN = "El Salvador", NameES = "El Salvador", Capital = "San Salvador", Continent = "América", TimeZone = "UTC-06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 71, NameEN = "Equatorial Guinea", NameES = "Guinea Ecuatorial", Capital = "Malabo", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 72, NameEN = "Eritrea", NameES = "Eritrea", Capital = "Asmara", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 73, NameEN = "Estonia", NameES = "Estonia", Capital = "Tallín", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 74, NameEN = "Eswatini ", NameES = "Suazilandia", Capital = "Mbabane", Continent = "África", TimeZone = "UTC+02:00", Territory = "Swaziland", Default = true });
        list.Add(new Country() { IdCountry = 75, NameEN = "Ethiopia", NameES = "Etiopía", Capital = "Adís Abeba", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 76, NameEN = "Fiji", NameES = "Fiyi", Capital = "Suva", Continent = "Oceanía", TimeZone = "UTC+12:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 77, NameEN = "Finland", NameES = "Finlandia", Capital = "Helsinki", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 78, NameEN = "Gabon", NameES = "Gabón", Capital = "Libreville", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 79, NameEN = "Gambia", NameES = "Gambia", Capital = "Banjul", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 80, NameEN = "Georgia", NameES = "Georgia", Capital = "Tiflis", Continent = "Europa", TimeZone = "UTC+04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 81, NameEN = "Germany", NameES = "Alemania", Capital = "Berlín", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 82, NameEN = "Ghana", NameES = "Ghana", Capital = "Accra", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 83, NameEN = "Greece", NameES = "Grecia", Capital = "Atenas", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 84, NameEN = "Grenada", NameES = "Granada", Capital = "Saint George'S", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 85, NameEN = "Guatemala", NameES = "Guatemala", Capital = "Ciudad De Guatemala", Continent = "América", TimeZone = "UTC-06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 86, NameEN = "Guinea", NameES = "Guinea", Capital = "Conakry", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 87, NameEN = "Guinea-Bissau", NameES = "Guinea-Bissau", Capital = "Bissau", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 88, NameEN = "Guyana", NameES = "Guyana", Capital = "Georgetown", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 89, NameEN = "Haiti", NameES = "Haití", Capital = "Puerto Príncipe", Continent = "América", TimeZone = "UTC-05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 90, NameEN = "Honduras", NameES = "Honduras", Capital = "Tegucigalpa", Continent = "América", TimeZone = "UTC-06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 91, NameEN = "Hong Kong", NameES = "Hong Kong", Capital = "Hong Kong", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 92, NameEN = "Hungary", NameES = "Hungría", Capital = "Budapest", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 93, NameEN = "Iceland", NameES = "Islandia", Capital = "Reikiavik", Continent = "Europa", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 94, NameEN = "India", NameES = "India", Capital = "Nueva Delhi", Continent = "Asia", TimeZone = "UTC+05:30", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 95, NameEN = "Iran", NameES = "Irán", Capital = "Teherán", Continent = "Asia", TimeZone = "UTC+03:30", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 96, NameEN = "Iraq", NameES = "Iraq", Capital = "Bagdad", Continent = "Asia", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 97, NameEN = "Ireland", NameES = "Irlanda", Capital = "Dublín", Continent = "Europa", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 98, NameEN = "Israel", NameES = "Israel", Capital = "Jerusalén", Continent = "Asia", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 99, NameEN = "Italy", NameES = "Italia", Capital = "Roma", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 100, NameEN = "Ivory Coast", NameES = "Costa de Marfil", Capital = "Yamusukro, Abiyán", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 101, NameEN = "Jamaica", NameES = "Jamaica", Capital = "Kingston", Continent = "América", TimeZone = "UTC-05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 102, NameEN = "Japan", NameES = "Japón", Capital = "Tokio", Continent = "Asia", TimeZone = "UTC+09:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 103, NameEN = "Jordan", NameES = "Jordania", Capital = "Ammán", Continent = "Asia", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 104, NameEN = "Kenya", NameES = "Kenia", Capital = "Nairobi", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 105, NameEN = "Korea, North", NameES = "Corea del Norte", Capital = "Pyongyang", Continent = "Asia", TimeZone = "UTC+09:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 106, NameEN = "Korea, South", NameES = "Corea del Sur", Capital = "Seúl", Continent = "Asia", TimeZone = "UTC+09:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 107, NameEN = "Kuwait", NameES = "Kuwait", Capital = "Ciudad De Kuwait", Continent = "Asia", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 108, NameEN = "Kyrgyzstan", NameES = "Kirguistán", Capital = "Biskek", Continent = "Asia", TimeZone = "UTC+06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 109, NameEN = "Laos", NameES = "Laos", Capital = "Vientián", Continent = "Asia", TimeZone = "UTC+07:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 110, NameEN = "Latvia", NameES = "Letonia", Capital = "Riga", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 111, NameEN = "Lebanon", NameES = "Líbano", Capital = "Beirut", Continent = "Asia", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 112, NameEN = "Lesotho", NameES = "Lesoto", Capital = "Maseru", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 113, NameEN = "Liberia", NameES = "Liberia", Capital = "Monrovia", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 114, NameEN = "Libya", NameES = "Libia", Capital = "Trípoli", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 115, NameEN = "Liechtenstein", NameES = "Liechtenstein", Capital = "Vaduz", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 116, NameEN = "Lithuania", NameES = "Lituania", Capital = "Vilna", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 117, NameEN = "Luxembourg", NameES = "Luxemburgo", Capital = "Luxemburgo", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 118, NameEN = "Macau", NameES = "Macao", Capital = "Macao", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 119, NameEN = "Madagascar", NameES = "Madagascar", Capital = "Antananarivo", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 120, NameEN = "Malawi", NameES = "Malaui", Capital = "Lilongüe", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 121, NameEN = "Malaysia", NameES = "Malasia", Capital = "Kuala Lumpur", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 122, NameEN = "Maldives", NameES = "Maldivas", Capital = "Malé", Continent = "Asia", TimeZone = "UTC+05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 123, NameEN = "Mali", NameES = "Mali", Capital = "Bamako", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 124, NameEN = "Malta", NameES = "Malta", Capital = "La Valeta", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 125, NameEN = "Marshall Islands", NameES = "Islas Marshall", Capital = "Majuro", Continent = "Oceanía", TimeZone = "UTC+12:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 126, NameEN = "Mauritania", NameES = "Mauritania", Capital = "Nuakchot", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 127, NameEN = "Mauritius", NameES = "Mauricio", Capital = "Port Louis", Continent = "África", TimeZone = "UTC+04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 128, NameEN = "Moldova", NameES = "Moldavia", Capital = "Chisinau", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 129, NameEN = "Monaco", NameES = "Mónaco", Capital = "Mónaco", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 130, NameEN = "Montenegro", NameES = "Montenegro", Capital = "Podgorica", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 131, NameEN = "Morocco", NameES = "Marruecos", Capital = "Rabat", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 132, NameEN = "Mozambique", NameES = "Mozambique", Capital = "Maputo", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 133, NameEN = "Myanmar", NameES = "Myanmar", Capital = "Naypyidaw", Continent = "Asia", TimeZone = "UTC+06:30", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 134, NameEN = "Namibia", NameES = "Namibia", Capital = "Windhoek", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 135, NameEN = "Nauru", NameES = "Nauru", Capital = "Yaren", Continent = "Oceanía", TimeZone = "UTC+12:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 136, NameEN = "Nepal", NameES = "Nepal", Capital = "Katmandú", Continent = "Asia", TimeZone = "UTC+05:45", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 137, NameEN = "Nicaragua", NameES = "Nicaragua", Capital = "Managua", Continent = "América", TimeZone = "UTC-06:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 138, NameEN = "Niger", NameES = "Níger", Capital = "Niamey", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 139, NameEN = "Nigeria", NameES = "Nigeria", Capital = "Abuya", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 140, NameEN = "North Macedonia", NameES = "República De Macedonia", Capital = "Skopje", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 141, NameEN = "Norway", NameES = "Noruega", Capital = "Oslo", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 142, NameEN = "Oman", NameES = "Omán", Capital = "Mascate", Continent = "Asia", TimeZone = "UTC+04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 143, NameEN = "Pakistan", NameES = "Pakistán", Capital = "Islamabad", Continent = "Asia", TimeZone = "UTC+05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 144, NameEN = "Palau", NameES = "Palaos", Capital = "Melekeok", Continent = "Oceanía", TimeZone = "UTC+09:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 145, NameEN = "Palestine", NameES = "Palestina", Capital = "Ramala", Continent = "Asia", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 146, NameEN = "Panama", NameES = "Panamá", Capital = "Ciudad De Panamá", Continent = "América", TimeZone = "UTC-05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 147, NameEN = "Paraguay", NameES = "Paraguay", Capital = "Asunción", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 148, NameEN = "Peru", NameES = "Perú", Capital = "Lima", Continent = "América", TimeZone = "UTC-05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 149, NameEN = "Philippines", NameES = "Filipinas", Capital = "Manila", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 150, NameEN = "Poland", NameES = "Polonia", Capital = "Varsovia", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 151, NameEN = "Qatar", NameES = "Catar", Capital = "Doha", Continent = "Asia", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 152, NameEN = "Romania", NameES = "Rumania", Capital = "Bucarest", Continent = "Europa", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 153, NameEN = "Rwanda", NameES = "Ruanda", Capital = "Kigali", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 154, NameEN = "Saint Kitts and Nevis", NameES = "San Cristóbal y Nieves", Capital = "Basseterre", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 155, NameEN = "Saint Lucia", NameES = "Santa Lucía", Capital = "Castries", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 156, NameEN = "Saint Vincent and the Grenadines", NameES = "San Vicente y las Granadinas", Capital = "Kingstown", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 157, NameEN = "Samoa", NameES = "Samoa", Capital = "Apia", Continent = "Oceanía", TimeZone = "UTC+13:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 158, NameEN = "San Marino", NameES = "San Marino", Capital = "Ciudad De San Marino", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 159, NameEN = "São Tomé and Príncipe", NameES = "Santo Tomé y Príncipe", Capital = "Santo Tomé", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 160, NameEN = "Saudi Arabia", NameES = "Arabia Saudita", Capital = "Riad", Continent = "Asia", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 161, NameEN = "Senegal", NameES = "Senegal", Capital = "Dakar", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 162, NameEN = "Serbia", NameES = "Serbia", Capital = "Belgrado", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 163, NameEN = "Seychelles", NameES = "Seychelles", Capital = "Victoria", Continent = "África", TimeZone = "UTC+04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 164, NameEN = "Sierra Leone", NameES = "Sierra Leona", Capital = "Freetown", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 165, NameEN = "Singapore", NameES = "Singapur", Capital = "Singapur", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 166, NameEN = "Slovakia", NameES = "Eslovaquia", Capital = "Bratislava", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 167, NameEN = "Slovenia", NameES = "Eslovenia", Capital = "Lublijana", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 168, NameEN = "Solomon Islands", NameES = "Islas Salomón", Capital = "Honiara", Continent = "Oceanía", TimeZone = "UTC+11:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 169, NameEN = "Somalia", NameES = "Somalia", Capital = "Mogadiscio", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 170, NameEN = "South Sudan", NameES = "Sudán del Sur", Capital = "Yuba", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 171, NameEN = "Sri Lanka", NameES = "Sri Lanka", Capital = "Sri Jayawardenapura", Continent = "Asia", TimeZone = "UTC+05:30", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 172, NameEN = "Sudan", NameES = "Sudán Del Norte", Capital = "Jartum", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 173, NameEN = "Suriname", NameES = "Surinam", Capital = "Paramaribo", Continent = "América", TimeZone = "UTC-03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 174, NameEN = "Sweden", NameES = "Suecia", Capital = "Estocolmo", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 175, NameEN = "Switzerland", NameES = "Suiza", Capital = "Berna", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 176, NameEN = "Syria", NameES = "Siria", Capital = "Damasco", Continent = "Asia", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 177, NameEN = "Taiwan", NameES = "Taiwan", Capital = "Taipeh", Continent = "Asia", TimeZone = "UTC+08:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 178, NameEN = "Tajikistan", NameES = "Tayikistán", Capital = "Dusambé", Continent = "Asia", TimeZone = "UTC+05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 179, NameEN = "Tanzania", NameES = "Tanzania", Capital = "Dodoma", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 180, NameEN = "Thailand", NameES = "Tailandia", Capital = "Bangkok", Continent = "Asia", TimeZone = "UTC+07:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 181, NameEN = "Togo", NameES = "Togo", Capital = "Lomé", Continent = "África", TimeZone = "UTC+00:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 182, NameEN = "Tonga", NameES = "Tonga", Capital = "Nuku'Alofa", Continent = "Oceanía", TimeZone = "UTC+13:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 183, NameEN = "Trinidad and Tobago", NameES = "Trinidad y Tobago", Capital = "Puerto España", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 184, NameEN = "Tunisia", NameES = "Túnez", Capital = "Túnez", Continent = "África", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 185, NameEN = "Turkey", NameES = "Turquía", Capital = "Ankara", Continent = "Asia", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 186, NameEN = "Turkmenistan", NameES = "Turkmenistán", Capital = "Asjabad", Continent = "Asia", TimeZone = "UTC+05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 187, NameEN = "Tuvalu", NameES = "Tuvalu", Capital = "Funafuti", Continent = "Oceanía", TimeZone = "UTC+12:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 188, NameEN = "Uganda", NameES = "Uganda", Capital = "Kampala", Continent = "África", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 189, NameEN = "United Arab Emirates", NameES = "Emiratos Arabes Unidos", Capital = "Abu Dabi", Continent = "Asia", TimeZone = "UTC+04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 190, NameEN = "Uruguay", NameES = "Uruguay", Capital = "Montevideo", Continent = "América", TimeZone = "UTC-03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 191, NameEN = "Uzbekistan", NameES = "Uzbekistán", Capital = "Tashkent", Continent = "Asia", TimeZone = "UTC+05:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 192, NameEN = "Vanuatu", NameES = "Vanuatu", Capital = "Port Vila", Continent = "Oceanía", TimeZone = "UTC+11:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 193, NameEN = "Vatican City", NameES = "Vaticano", Capital = "Ciudad Del Vaticano", Continent = "Europa", TimeZone = "UTC+01:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 194, NameEN = "Venezuela", NameES = "Venezuela", Capital = "Caracas", Continent = "América", TimeZone = "UTC-04:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 195, NameEN = "Vietnam", NameES = "Vietnam", Capital = "Hanoi", Continent = "Asia", TimeZone = "UTC+07:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 196, NameEN = "Yemen", NameES = "Yemen", Capital = "Saná", Continent = "Asia", TimeZone = "UTC+03:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 197, NameEN = "Zambia", NameES = "Zambia", Capital = "Lusaka", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });
        list.Add(new Country() { IdCountry = 198, NameEN = "Zimbabwe", NameES = "Zimbabue", Capital = "Harare", Continent = "África", TimeZone = "UTC+02:00", Territory = "", Default = true });

        return list;
    }
}
